name: CI Tests

on:
  pull_request:
    branches: [ release ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Rich (pip)
  FORCE_COLOR: 1
  # Tox
  PY_COLORS: 1
  # Mypy (see https://github.com/python/mypy/issues/7771)
  TERM: xterm-color

jobs:

  ci:
    name: CI
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 2
      - name: cache salad
        uses: actions/cache@v3
        with:
          path: ${HOME}/.cache/salad
          key: schema_salad
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: ci.py

      - name: Upgrade setuptools and install tox
        run: |
          pip install -U pip setuptools wheel
          pip install cwltool crayons

      - name: Run checks
        run: python ci.py
